"""pycauchykesai native 模块（pybind11 绑定）的类型存根.

实际实现为编译产物 pycauchykesai.*.so（C++ + pybind11），无 Python 源码.
本 .pyi 为 mypy / IDE 提供类型签名，让静态检查能识别 native 类与方法.
完整行为见 docs/cn_CauchyKesai_Auto.md 与 docs/cn_CauchyKesai_with_IONArray.md.
"""

from __future__ import annotations

from typing import Any, overload

import numpy as np
from numpy.typing import NDArray

# ── 模块级 C 桥：SDK 芯片 / 库查询（无参、不依赖模型）──────────────────────
def soc_name() -> str: ...
def dnn_version() -> str: ...
def bpu_version() -> str: ...

# ── IONArrayDesc：纯张量描述（无内存），成员 public 直访 ──────────────────
class IONArrayDesc:
    def __init__(self, dtype: np.dtype[Any], shape: list[int]) -> None: ...

    # 成员 public（直访，无 getter）
    dtype: np.dtype[Any]
    shape: list[int]
    name: str
    desc: str
    aligned_byte_size: int
    tensor_type: int
    quanti_type: int
    quantize_axis: int
    stride: list[int]
    scale: list[float]
    zero_point: list[int]

    # 计算方法（有逻辑）
    def ndim(self) -> int: ...
    def size(self) -> int: ...
    def nbytes(self) -> int: ...
    def has_stride(self) -> bool: ...
    def is_padded_layout(self) -> bool: ...
    def has_tensor_properties(self) -> bool: ...
    def is_quantized(self) -> bool: ...


# ── IONArray：持有 desc + memory，class，成员 public 直访 ──────────────────
class IONArray:
    @overload
    def __init__(
        self,
        dtype: np.dtype[Any],
        shape: list[int],
        cached: bool = ...,
        defer: bool = ...,
    ) -> None: ...
    @overload
    def __init__(
        self,
        desc: IONArrayDesc,
        cached: bool = ...,
        defer: bool = ...,
    ) -> None: ...

    # 成员 public（直访）
    desc: IONArrayDesc
    memory: IONMemory
    byte_offset: int

    # 懒分配
    def allocate(self, cached: bool = ...) -> None: ...

    # 内存属性
    @property
    def is_allocated(self) -> bool: ...

    # Cache 操作
    def flush_clean(self) -> None: ...
    def flush_invalidate(self) -> None: ...

    # numpy 视图
    def numpy(self) -> NDArray[Any]: ...
    def __array__(self, dtype: Any = ...) -> NDArray[Any]: ...

    # 工厂：共享 IONMemory + 偏移 + 从描述继承 tensor 性质（template 可为 IONArrayDesc 或 IONArray）
    @staticmethod
    def from_memory(memory: IONMemory, byte_offset: int, template: IONArrayDesc) -> IONArray: ...

    # 量化 / 反量化
    def dequantize(self) -> NDArray[Any]: ...
    def quantize(self, float_arr: NDArray[Any]) -> None: ...

    # 布局感知写入（写后自动 flush_clean）
    def from_numpy(self, arr: NDArray[Any]) -> None: ...

    # 模块级 from_numpy 工厂的 C++ 落地（allocate + from_numpy + flush）。
    # __init__ 加 `from_numpy = IONArray.from_numpy_array` re-export 满足模块级 import 契约。
    @staticmethod
    def from_numpy_array(arr: NDArray[Any], cached: bool = ...) -> IONArray: ...

# ── IONMemory：裸 ION 物理内存块（无 tensor 语义）──────────────────────────
class IONMemory:
    def __init__(self, size: int, cached: bool = ...) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def is_allocated(self) -> bool: ...
    def flush_clean(self) -> None: ...
    def flush_invalidate(self) -> None: ...

    # 固定 uint8 一维 raw bytes 视图（capsule 保活）
    def numpy(self) -> NDArray[np.uint8]: ...

# ── Platform：板卡 / 芯片平台原子能力（机型无关，不依赖加载模型）────────────
# 8 静态 property（构造时缓存）+ 7 实时方法（每次现读 sysfs）+ summary()。
# s() 展示留 Python wrapper（调 _render.render_platform），native 不绑 s()。
class Platform:
    def __init__(self) -> None: ...

    # 8 静态属性（只读，构造时缓存）
    @property
    def soc_name(self) -> str: ...
    @property
    def bpu_type(self) -> str: ...
    @property
    def dnn_version(self) -> str: ...
    @property
    def bpu_version(self) -> str: ...
    @property
    def physical_core_num(self) -> int: ...
    @property
    def cpu_model(self) -> str: ...
    @property
    def cpu_count(self) -> int: ...
    @property
    def mem_total_mb(self) -> int: ...

    # 7 实时方法（每次现读 sysfs / proc）
    def bpu_rate(self) -> list[int]: ...
    def bpu_freq(self) -> list[int]: ...
    def cpu_freq(self) -> list[int]: ...
    def temperature(self, name: str = ...) -> dict[str, Any]: ...
    def voltage(self, name: str = ...) -> dict[str, Any]: ...
    def ion_memory(self, name: str = ...) -> dict[str, Any]: ...
    def ucp_library_path(self) -> str: ...

    # summary / repr（s() 反调 Python _render.render_platform）
    def summary(self) -> dict[str, Any]: ...
    def s(self) -> None: ...
    def __repr__(self) -> str: ...

# BPU 固件版本（bpu0/fw_version；模型加载后才初始化）。CauchyKesai.summary() 内部注入。
def read_bpu_fw_version() -> str: ...

# ── CauchyKesai：BPU 推理编排器（native 基类，Python wrapper 在 __init__ 继承）──
# 设计：ION 层 = 原子零拷贝能力；Auto 档 = ION 原子的组合（不重写路径，调 ION 原子）。
class CauchyKesai:
    def __init__(
        self,
        model_path: str,
        n_task: int = ...,
        model_cnt_select: int = ...,
    ) -> None: ...

    # 信息查询：summary()/benchmark() 返 dict；s()/t() 由 Python wrapper 覆盖为 print
    def summary(self) -> dict[str, Any]: ...
    def benchmark(self, timeout_ms: int = ...) -> dict[str, float]: ...
    def is_busy(self, task_id: int = ...) -> bool: ...

    # ── 异步推理入口（不校验 bound：快/浅）──
    # start(task_id=0)：零拷贝提交（用 slot 已绑定的 IONArray，不传 inputs）
    @overload
    def start(self, task_id: int = ...) -> None: ...
    # start(inputs, task_id=0)：Auto memcpy 提交（from_numpy 写 slot 的 IONArray，再走零拷贝 start）
    @overload
    def start(self, inputs: list[NDArray[Any]], task_id: int = ...) -> None: ...
    def start(self, *args: Any, **kwargs: Any) -> None: ...

    # wait_done：纯等完成（flush_invalidate 输出 + release task），不返回
    def wait_done(self, task_id: int = ..., timeout_ms: int = ...) -> None: ...
    # wait：wait_done + 导出 list[ndarray]（Auto 用）
    def wait(self, task_id: int = ..., timeout_ms: int = ...) -> list[NDArray[Any]]: ...

    # ── 同步推理入口（校验 bound：check_input/output，不匹配抛）──
    # __call__(inputs, task_id=0)：Auto 同步 memcpy（校验 dtype/ndim/shape + from_numpy + start + wait + 导出）
    @overload
    def __call__(self, inputs: list[NDArray[Any]], task_id: int = ...) -> list[NDArray[Any]]: ...
    # __call__(task_id=0)：零拷贝同步（校验 bound + start + wait + 导出）
    @overload
    def __call__(self, *, task_id: int = ...) -> list[NDArray[Any]]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> list[NDArray[Any]]: ...

    # ── 校验能力（同步接口内部调 + Python 暴露；返回 bool 不抛）──
    def check_input(self, ion: IONArray, idx: int) -> bool: ...
    def check_output(self, ion: IONArray, idx: int) -> bool: ...

    # ── bound IONArray（def_readwrite，public）：m.inputs[slot][idx]=ion 纯赋值，无校验 ──
    inputs: list[list[IONArray]]
    outputs: list[list[IONArray]]

    # ── 模板 desc（模型固有性质，只读）──
    @property
    def input_descs(self) -> list[IONArrayDesc]: ...
    @property
    def output_descs(self) -> list[IONArrayDesc]: ...

    # 只读属性 / 计数
    input_names: list[str]
    output_names: list[str]
    @property
    def bpu_core_num(self) -> int: ...
    @property
    def platform(self) -> Platform: ...
    @property
    def n_task(self) -> int: ...
    @property
    def input_count(self) -> int: ...
    @property
    def output_count(self) -> int: ...

    # BPU 核调度（per-slot 核掩码）
    def scheduled_cores(self, task_id: int = ...) -> list[int]: ...
    def scheduled_priority(self, task_id: int = ...) -> int: ...
    def set_scheduling_params(self, bpu_cores: list[int], priority: int = ..., task_id: int = ...) -> None: ...
